language: java

jdk:
-openjdk11

dist: trusty

addons:
  sonarcloud:
    organization: "Emptyiles3-github"

sudo: false # faster builds

script: 
-"mvn cobertura:cobertura"
- sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)


